

services:
  db:
    image: postgres:15-alpine
    container_name: postificus_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postificus
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d postificus"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: postificus_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_net

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: postificus_rabbitmq
    restart: always
    ports:
      - "5672:5672"   # AMQP protocol
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app_net

  minio:
    image: minio/minio:latest
    container_name: postificus_s3
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - app_net

  api:
    build: .
    container_name: postificus_api
    command: ["./postificus-api"] # Command to run Echo
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/postificus?sslmode=disable
      - REDIS_URL=redis://postificus_redis:6379
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_PUBLIC_URL=http://localhost:9000
      - APP_ENV=production
      # Auth Keys
      - MEDIUM_UID=${MEDIUM_UID}
      - MEDIUM_SID=${MEDIUM_SID}
      - MEDIUM_XSRF=${MEDIUM_XSRF}
      - DEVTO_SESSION_TOKEN=${DEVTO_SESSION_TOKEN}
      - LI_AT=${LI_AT}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
    networks:
      - app_net

  worker:
    build: .
    container_name: postificus_worker
    command: ["./postificus-worker"] # Command to run Worker
    restart: always
    environment:
      - BROWSER_HEADLESS=true
      - DATABASE_URL=postgres://user:password@db:5432/postificus?sslmode=disable
      - REDIS_URL=redis://postificus_redis:6379
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - APP_ENV=production
      # Auth Keys
      - MEDIUM_UID=${MEDIUM_UID}
      - MEDIUM_SID=${MEDIUM_SID}
      - MEDIUM_XSRF=${MEDIUM_XSRF}
      - DEVTO_SESSION_TOKEN=${DEVTO_SESSION_TOKEN}
      - LI_AT=${LI_AT}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
    networks:
      - app_net

  grafana-agent:
    image: grafana/agent:latest
    container_name: postificus_grafana_agent
    volumes:
      - ./grafana/agent/agent.yaml:/etc/agent/agent.yaml
    environment:
      - GRAFANA_CLOUD_PROM_URL
      - GRAFANA_CLOUD_PROM_USERNAME
      - GRAFANA_CLOUD_PROM_PASSWORD
    command:
      - "-config.file=/etc/agent/agent.yaml"
      - "-config.expand-env"
    depends_on:
      - api
    networks:
      - app_net



volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
  minio_data:

networks:
  app_net:
    driver: bridge
